checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - tests/*

build:
  nodes:
    coverage:
      project_setup:
        override:
          - pip install coverage
      tests:
        override:
          - command: 'coverage run -m pytest'
            coverage:
              file: '.coverage'
              format: 'py-cc'
    analysis:
      tests:
        override:
          - py-scrutinizer-run