checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            test_default:
                override:
                    - py-scrutinizer-run
                    -
                        command: pylint-run
                        use_website_config: true
            test_personal:
                before:
                  - pip install coverage
                  - pip install pytest
                override:
                  -
                      command: coverage run -m pytest
                      coverage:
                        file: .coverage
                        format: python-cc
filter:
    excluded_paths:
        - '*/test/*'
    dependency_paths:
        - 'lib/*'