checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
              before:
                - pip install pytest coverage
                  override:
                      - py-scrutinizer-run
                      -
                          command: pylint-run
                          use_website_config: true
                      -
                          command: coverage run -m pytest
                          coverage:
                            file: .coverage
filter:
    excluded_paths:
        - '*/test/*'
    dependency_paths:
        - 'lib/*'