checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
              before:
                - pip install coverage pytest
                override:
                    - py-scrutinizer-run
                    - coverage run -m pytest
                    -
                        command: pylint-run
                        use_website_config: true
                  coverage:
                    file: .coverage
                    format: py-cc
filter:
    excluded_paths:
        - '*/test/*'
    dependency_paths:
        - 'lib/*'