checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - tests/*

build:
  project_setup:
    override:
      - pip install coverage pytest re yaml tkinter shutil gettext
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
          - command: 'coverage run -m pytest'
            coverage:
              file: '.coverage'
              format: 'py-cc'
