checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - py-scrutinizer-run
                    -
                        command: pylint-run
                        use_website_config: true
                  coverage:
                    file: .coverage
                    format: python-cc
filter:
    excluded_paths:
        - '*/test/*'
        - '*/tests/*'
    dependency_paths:
        - 'lib/*'
