language: python
python:
# После введения аннотаций тесты на 3.7 и 3.8 перестали проходить
#  - "3.7"
#  - "3.8"
  - "3.9"
# В TravisCI пока нет 3.10
#  - "3.10"

install:
  - sudo apt-get install -y python3-tk
  - pip install coverage pytest regex pyyaml coveralls

services:
  - xvfb

script:
  - coverage run -m pytest
  - coveralls