language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
#  - "3.10"

install:
  - sudo apt-get install -y python3-tk
  - pip install coverage pytest regex pyyaml coveralls

services:
  - xvfb

script:
  - coverage run -m pytest
  - coveralls